name: flutter_zwicon
description: "ZWIcons is a fast and easy to use library of icons with 566 icons in 26 categories, designed on a 24px grid"
version: 1.0.0
repository: https://github.com/SamMotta/flutter_zwicons

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  recase: ^4.1.0

flutter:
  uses-material-design: true
  fonts:
    - family: ZwIcons
      fonts:
        - asset: ./fonts/zwicon.ttf
          weight: 500
