// ignore_for_file: avoid_print

import 'dart:convert';
import 'dart:io';

import 'package:recase/recase.dart';

void main(List<String> args) {
  File iconsFile = File(args[0]);

  if (!iconsFile.existsSync()) {
    print("File not found!");
    exit(0);
  }

  String content = iconsFile.readAsStringSync();
  List<dynamic> icons = json.decode(content);

  List<String> genOutput = [
    "library flutter_zwicons;\n",
    "import \"package:flutter/widgets.dart\";\n",
    "import \"package:flutter_zwicon/src/icon_data.dart\";\n\n",
    "// THIS FILE IS AUTOMATICALLY GENERATED!\n\n",
    "class ZWIcons {\n"
  ];

  for (Map<String, dynamic> icon in icons) {
    icon.forEach(
      (String iconName, dynamic iconCode) => genOutput.add(
        "  static const IconData ${ReCase(iconName).camelCase} = ZwIconData(0x$iconCode);\n",
      ),
    );
  }

  genOutput.add("}\n");

  File output = File('./lib/flutter_zwicon.dart');
  output.writeAsStringSync(genOutput.join());
}
